export * from "./cities";
export * from "./colors";
export * from "./jobs";
export * from "./sexes";
export * from "./shifts";
export * from "./specialties";
export * from "./streets";
export * from "./surnames";
export * from "./types-of-diagnoses";
